---
title: "EnWAS V2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libs
```{r libs,warning=FALSE,message=FALSE}
library(DBI)
library(survey)
library(broom)
library(splines)
library(stringr)
library(dplyr)
library(ggplot2)

```

## Load exploration

- select_vars.txt was generated by [variable selection process](https://ccb-hms.github.io/Imputation/diet_var_selection.html)
- `nhanes.sqlite` can download [here](https://github.com/ccb-hms/Imputation/blob/main/nhanes.sqlite) or generate by run [notebook](https://ccb-hms.github.io/Imputation/nhanes_exploratory.html)

```{r data, echo=TRUE}
source("phesant.R")

exposure_vars <-
  read.delim("data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "nhanes.sqlite")
  
  cols <-
    'BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)
  
  phs_res <- phesant(data)
  
  data[, names(phs_res[phs_res %in% c("ordered", "unordered", "binary")])] <-
    lapply(data[, names(phs_res[phs_res %in% c("ordered", "unordered", "binary")])], as.factor)
  
  data[, names(phs_res[phs_res == "continuous"])] <-
    lapply(data[, names(phs_res[phs_res == "continuous"])], as.numeric)
  
  return(list(data = data, phs_res = phs_res))
  
}

data_phs <- load_data(exposure_cols)

data <- data_phs$data
phs_res <- data_phs$phs_res

```


## Inverse Normal Distribution and build formula

```{r func, echo=TRUE}
invNorm <- function(x) {qnorm((rank(x) - 3/8)/(length(x) +1 - 6/8))}
min_max_norm <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}


build_formula <- function(base_model,exposure_var,inv=FALSE) {
  var <- "+ %s"
  if(inv) var <- " + invNorm(%s)" 
  
  as.formula(
    sprintf(paste0(base_model, var),
      exposure_var
    )
  )
}


```



## EnWAS

```{r func2, echo=TRUE}

data$fouryearwt <- data$WTDRD1 / 2
dsn <- svydesign(
  ids = ~ SDMVPSU,
  weights = ~ fouryearwt,
  strata = ~ SDMVSTRA,
  data = data,
  nest = TRUE
)


enwas <- function(base_model, exposure_vars, dsn, inv = FALSE) {
  association_list <- data.frame() # step 2 of algorithm
  model_list <- c()
  for (exposure in exposure_vars) {
    model <- build_formula(base_model, exposure, inv)
    ## now run the association
    mod <- svyglm(model, dsn)
    model_list <- c(model_list, mod)
    mod_df <- tidy(mod)
    mod_df$variable <- exposure
    association_list <-
      rbind(association_list, mod_df) # step 3b of algorithm
  }
  
  # process results
  xwas_association_list <-
    association_list[association_list$term %in% exposure_vars,]
  # xwas_association_list <- association_list[association_list$term %in% c(exposure_vars,paste0("invNorm(",exposure_vars,")")), ]
  # xwas_association_list$term <- str_replace_all(xwas_association_list$term, "invNorm", "")
  # xwas_association_list$term <- str_replace_all(xwas_association_list$term, "[[:punct:]]", "")
  
  xwas_association_list$fdr <-
    p.adjust(xwas_association_list$p.value, method = 'BY')
  xwas_association_list <- xwas_association_list |>
    mutate(coff = estimate * std.error)  |>
    mutate(lower = estimate - 1.96 * std.error)  |>
    mutate(upper = estimate + 1.96 * std.error)
  
  return (list(model_list= model_list, enwas_res = xwas_association_list))
  
}

forest_plot <- function(xwas_result) {
  xwas_result |>
    ggplot(aes(
      x = variable,
      y = estimate,
      ymin = lower,
      ymax = upper,
      colour = estimate
    )) +
    geom_pointrange() +
    coord_flip() +  # flip coordinates (puts labels on y axis)
    xlab("Exposures") + ylab("Estimate (95% CI)") +
    theme_bw()  # use a white background
}


forest_plot_mult <- function(xwas_result_list) {
  xwas_result <- do.call("rbind", xwas_result_list)
  xwas_result$EnWAS <-
    rep(names(xwas_result_list), each = nrow(xwas_result_list[[1]]))
  
  xwas_result |>
    ggplot(aes(
      x = variable,
      y = estimate,
      ymin = lower,
      ymax = upper,
      colour = EnWAS
    )) +
    geom_pointrange(alpha = 0.4) +
    coord_flip() +  # flip coordinates (puts labels on y axis)
    xlab("Exposures") + ylab("Estimate (95% CI)") +
    theme_bw()  # use a white background
}


```


## EnWAS Results

```{r func3, echo=TRUE,warning=F}
base_model <-
  'BMXWAIST ~ bs(RIDAGEYR, df = 7)*RIAGENDR + bs(BMXWT) + BMXHT'
enwas_res <- enwas(base_model, exposure_vars, dsn)
# forest_plot(enwas_res)


linear_model <- 'BMXWAIST ~ RIDAGEYR+RIAGENDR + BMXWT + BMXHT'
linear_res2 <- enwas(linear_model, exposure_vars, dsn)
# forest_plot(linear_res2)



age_knots <- seq(20, 90, by = 80)
q <- 10
bmi_knots = quantile(unique(invNorm(data$BMXBMI)), 1:(q - 2) / (q - 1))

age_ns_model <-
  'BMXWAIST ~ ns(RIDAGEYR, knots = seq(30, 80, by = 10)) * RIAGENDR + ns(BMXBMI,knots = seq(30, 80, by = 10)) + BMXWT + BMXHT'
age_ns_res <- enwas(age_ns_model, exposure_vars, dsn)



all_ns_model <-
  'BMXWAIST ~ ns(RIDAGEYR, knots = seq(30, 80, by = 10)) * RIAGENDR + ns(BMXBMI,knots = seq(30, 80, by = 10)) + ns(BMXWT) + ns(BMXHT, knots = seq(40, 200, by = 10))'
all_ns_res <- enwas(all_ns_model, exposure_vars, dsn)


ns_inverseNorm_model <-
  'BMXWAIST ~ ns(invNorm(RIDAGEYR),df=7) * RIAGENDR + ns(invNorm(BMXBMI)) + ns(invNorm(BMXWT)) + ns(invNorm(BMXHT))'
all_ns_inverse_res <- enwas(ns_inverseNorm_model, exposure_vars, dsn)



forest_plot_mult(
  list(
    bs_age = enwas_res$enwas_res,
    linear = linear_res2$enwas_res,
    ns_age = age_ns_res$enwas_res,
    ns_all = all_ns_res$enwas_res,
    ns_invNorm = all_ns_inverse_res$enwas_res
  )
)
  
```


