---
title: "transformation comparison"
output: html_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```




```{r setup,warning=FALSE,message=FALSE}
library(EnWAS)
library(splines)
library(ggplot2)
library(ggpubr)
library(dplyr)

library(DBI)
nhanes_db <- DBI::dbConnect(RSQLite::SQLite(), "../nhanes.sqlite")

```

## LBDBSESI   LBXBSE

```{r LBDBSESI,warning=FALSE,message=FALSE}


plot_trans <- function(x){
  layout(matrix(c(1,2,3), ncol=3, byrow=TRUE))
  par(mar=c(4.0,4.0,3.5,1))
  x <- na.omit(x)
  hist(x,main = "none")
  log(x+1e-5) |> scale() |> hist(main="log-Z")
  invNorm(x) |> hist(main="INVT")  
}

```


```{r LBDBSESI2,warning=FALSE,message=FALSE,dpi=200}
df_ctms <- dbGetQuery(nhanes_db, "SELECT LBDBSESI, LBXBSE from CadmiumLeadTotalMercurySeleniumAndManganeseBlood")
plot_trans(df_ctms$LBDBSESI)

```
```{r LBXBSE,warning=FALSE,message=FALSE,dpi=200}
plot_trans(df_ctms$LBXBSE)
```


```{r LBXBSE1,warning=FALSE,message=FALSE,dpi=200}

df_ctms <- dbGetQuery(nhanes_db, "select URXEQU, URXETD,URXETL,URXGNS from PhytoestrogensUrine")
plot_trans(df_ctms$URXEQU)
plot_trans(df_ctms$URXETD)
plot_trans(df_ctms$URXETL)

plot_trans(df_ctms$URXGNS)

df_ctms <- dbGetQuery(nhanes_db, "SELECT URX4FP,URXMAL, URXOPM from PyrethroidsHerbicidesAndOPMetabolitesUrine")
plot_trans(df_ctms$URX4FP)
plot_trans(df_ctms$URXMAL)
plot_trans(df_ctms$URXOPM)


df_ctms <- dbGetQuery(nhanes_db, "SELECT URXMZP,URXMCP, URXCNP from PhthalatesUrine")
plot_trans(df_ctms$URXMZP)
plot_trans(df_ctms$URXMCP)
plot_trans(df_ctms$URXCNP)

dbDisconnect(nhanes_db)
```

