---
title: "Explore Missing Data"

date: "Updated on : `r date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### configuration DB 

```{r data_config,warning=FALSE,message=FALSE}
sqlHost <- "localhost"
sqlUserName <- "sa"
sqlPassword <- "yourStrong(!)Password"
sqlDefaultDb <- "NhanesLandingZone"
```

## Load libs

```{r libs,warning=FALSE,message=FALSE}
library(naniar)
library(visdat)
library(corrplot)
library(phonto)
```





## Load data

```{r missing_r}
demo = phonto::nhanes('DEMO_E')
DT::datatable(demo)
```




## Missing pattern across variables (eg. age)

```{r missing}
gg_miss_fct(demo,fct = RIDAGEYR)

```

## show missing percentage

```{r missing1}
gg_miss_var(demo,show_pct = TRUE)

```

## Plot missing pattern

```{r miss_clipp,warning=FALSE}
vis_miss(demo,warn_large_data=FALSE)
```

## Missing Correlation

```{r}

missing_cols = sapply(demo, function(x)sum(is.na(x)))
missing_cols = missing_cols[missing_cols>0] # select the data with missing values
missing_cols

correlation = cor(is.na(demo[,names(missing_cols)]))
corrplot(correlation, type = "upper", order = "hclust",
         tl.col = "black", tl.srt = 45)
```





