---
title: "Query Data"
output: html_document
date: "Updated on : `r date()`"
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Setup 
Install the package for the first time.
`devtools::install_github("ccb-hms/phonto")`

```{r setup,warning=FALSE,message=FALSE}
library(phonto)
library(DT)
library(nhanesA)

```


## Step 1: search tables

It can be search by certain variable.

### 1) Check variables Consistency

```{r search_tables,warning=FALSE,message=FALSE}
checkDataConsistency("DEMO_C","DEMO_D") |> DT::datatable()
```

### 2) Union Query

```{r uniq,warning=FALSE,message=FALSE}
unionQuery(c("DEMO_B","DEMO_D"),c("RIDAGEYR","RIAGENDR")) |> DT::datatable()
```

### 3) Joint Query

```{r uniq2,warning=FALSE,message=FALSE}
jointQuery( list(BPQ_J=c("BPQ020", "BPQ050A"), DEMO_J=c("RIDAGEYR","RIAGENDR"))) |> DT::datatable()
```

```{r uniq3,warning=FALSE,message=FALSE}
cols = list(DEMO_I=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2","years"),
                     DEMO_J=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2","years"),
                     BPQ_I=c('BPQ050A','BPQ020'),BPQ_J=c('BPQ050A','BPQ020'),
                     HDL_I=c("LBDHDD"),HDL_J=c("LBDHDD"), TRIGLY_I=c("LBXTR","LBDLDL"),
            TRIGLY_J=c("LBXTR","LBDLDL"))
 ans =jointQuery(cols)
 ans|> DT::datatable()
```
