---
title: "exploring nonlinear associations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## load libs
```{r libs,warning=FALSE,message=FALSE}
library(DBI)
# library(broom)
library(splines)
# library(stringr)
library(dplyr)
library(ggplot2)
library(EnWAS)

```

## Load and Exploration

- select_vars.txt was generated by [variable selection process](https://ccb-hms.github.io/Imputation/7_enwas/diet_var_selection.html)
- `nhanes.sqlite` can download [here](https://github.com/ccb-hms/Imputation/blob/main/nhanes.sqlite) or generate by run [notebook](https://ccb-hms.github.io/Imputation/6_nhanes_data/nhanes_exploratory.html)

```{r data, echo=TRUE}
# source("../6_nhanes_data/phesant.R")

exposure_vars <-
  read.delim("../../data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
  
  cols <-
    'SEQN,BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA,RIDRETH1, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)
  
  data
  
}

nhanes_data <- load_data(exposure_cols) 
data_phs <- phesant(nhanes_data)

data <- data_phs$data
phs_res <- data_phs$data_types

```

## Query Extra data 

```{r query, echo=TRUE}
nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
cholesterol <- dbGetQuery(nhanes_db, "select * from cholesterol")
blood_pressure <- dbGetQuery(nhanes_db, "select SEQN,BPXDI1,BPXDI2,BPXSY1,years from blood_pressure")
dbDisconnect(nhanes_db)

```

# BPXDI1 - Diastolic: Blood pres (1st rdg) mm Hg

```{r BPXDI1, echo=TRUE,warning=FALSE}

data <- merge(blood_pressure, data, by = c("SEQN",'years'))

ggplot(data,
         aes(
           x = RIDAGEYR,
           y = BPXDI1,
           colour = RIAGENDR
         )) +
  geom_point(alpha = 0.1) +
  geom_smooth(
    method = lm,
    formula = y ~ ns(x, knots = seq(20, 80, by = 5)),
    size = 1
  )+
  geom_smooth(method = lm, formula = y ~ x)


ggplot(data, aes(x=BMXWT, y=BPXDI1) ) + 
  geom_point(aes(colour=RIAGENDR),alpha=0.1)+
  geom_density_2d()+geom_smooth(method = lm,formula = y ~ x)

```


## Run EnWAS 

```{r func3, echo=TRUE,warning=F, out.width = '90%'}
linear_model <- 'BPXDI1 ~ RIDAGEYR*RIAGENDR + BMXBMI'
linear_res2 <- enwas(linear_model, exposure_vars, data)


all_ns_model <-
  'BPXDI1 ~ ns(RIDAGEYR, knots = seq(20, 80, by = 10)) * RIAGENDR + ns(BMXBMI,knots = c(seq(15, 45, by = 5),seq(45,65,by=10)))'
all_ns_res <- enwas(all_ns_model, exposure_vars, data)


lm_inverse_res <- enwas(linear_model, exposure_vars, data,inv = TRUE)
ns_inverse_res <- enwas(all_ns_model, exposure_vars, data,inv = TRUE)


```


## Compare linear regression with spline regression.



```{r res3, echo=TRUE,warning=F, out.width = '90%'}
# forest_plot(linear_res2$enwas_res)


forest_plot_mult(
  list(
    linear = linear_res2$enwas_res,
    ns = all_ns_res$enwas_res
  )
)
```


```{r res4, echo=TRUE,warning=F, out.width = '90%'}
forest_plot_mult(
  list(
    lm_inv = lm_inverse_res$enwas_res,
    ns_inv = ns_inverse_res$enwas_res
  )
)
forest_plot_mult(
  list(
    linear = linear_res2$enwas_res,
    lm_inv = lm_inverse_res$enwas_res
  )
)
forest_plot_mult(
  list(
    ns = all_ns_res$enwas_res,
    ns_inv = ns_inverse_res$enwas_res
  )
)
  
```



