---
title: "EnWAS: Systolic-Blood Pressure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libs and Load data
The process of load libs and data is the same as [EnWAS sample](https://ccb-hms.github.io/Imputation/7_enwas/EnWAS_simple.html).

```{r data, warning=FALSE,message=FALSE,echo=FALSE}
# source("../6_nhanes_data/phesant.R")

library(DBI)
# library(broom)
library(splines)
# library(stringr)
library(dplyr)
library(ggplot2)
library(EnWAS)

exposure_vars <-
  read.delim("../../data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
  
  cols <-
    'SEQN,BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA,RIDRETH1, INDFMPIR, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)
  
  data
  
}

nhanes_data <- load_data(exposure_cols) 
data_phs <- phesant(nhanes_data)

data <- data_phs$data
phs_res <- data_phs$data_types

```

## Query Extra data 

```{r query, echo=TRUE}
nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
# demo <- dbGetQuery(nhanes_db, "select * from demo")
# cholesterol <- dbGetQuery(nhanes_db, "select * from cholesterol")
# BPXDI2,BPXSY1
blood_pressure <- dbGetQuery(nhanes_db, "select SEQN,BPXSY1,years from blood_pressure where BPXSY1 IS NOT NULL")
dbDisconnect(nhanes_db)

```

## BPXSY1 - Systolic: Blood pres (1st rdg) mm Hg

```{r BPXSY1, echo=TRUE,warning=FALSE}

data <- merge(blood_pressure, data, by = c("SEQN",'years'))

ggplot(data,
         aes(
           x = RIDAGEYR,
           y = BPXSY1,
           colour = RIAGENDR
         )) +
  geom_point(alpha = 0.1) +
  geom_smooth(
    method = lm,
    formula = y ~ ns(x, knots = seq(20, 80, by = 5)),
    size = 1
  )+
  geom_smooth(method = lm, formula = y ~ x)


ggplot(data, aes(x=BMXBMI, y=BPXSY1) ) + 
  geom_point(aes(colour=RIAGENDR),alpha=0.1)+
  geom_density_2d()+geom_smooth(method = lm,formula = y ~ x)

```


## Run EnWAS 

```{r func3, echo=TRUE,warning=F, out.width = '90%'}
lm_str <- 'BPXSY1 ~ RIDAGEYR*RIAGENDR + BMXBMI'
lm_enwas <- enwas(lm_str, exposure_vars, data)


ns_str <-
  'BPXSY1 ~ ns(RIDAGEYR, knots = seq(30, 80, by = 10), Boundary.knots=c(20,90)) * RIAGENDR + ns(BMXBMI,knots = c(seq(15, 45, by = 5),seq(45,65,by=10)),Boundary.knots=c(10,85))'
ns_enwas <- enwas(ns_str, exposure_vars, data)


lm_inverse_res <- enwas(lm_str, exposure_vars, data,inv = TRUE)
ns_inverse_res <- enwas(ns_str, exposure_vars, data,inv = TRUE)


```


## Compare linear regression with spline regression.



```{r res3, echo=TRUE,warning=F, out.width = '90%'}
# forest_plot(lm_enwas$enwas_res)


forest_plot_mult(
  list(
    linear = lm_enwas$enwas_res,
    ns = ns_enwas$enwas_res
  )
)
```


```{r res4, echo=TRUE,warning=F, out.width = '90%'}

forest_plot_mult(
  list(
    linear = lm_enwas$enwas_res,
    lm_inv = lm_inverse_res$enwas_res
  )
)

df <- data.frame("term"=c(lm_enwas$enwas_res$term,ns_enwas$enwas_res$term),
           "p.value"= c(lm_enwas$enwas_res$p.value,ns_enwas$enwas_res$p.value),
           'fdr'= c(lm_enwas$enwas_res$fdr,ns_enwas$enwas_res$fdr),
           "model" = c(rep("lm",52),rep("ns",52))
) 



g_p.value <- df|> ggplot(aes(term,p.value,color=model)) + 
  geom_segment( aes(x=term, xend=term, y=0, yend=p.value)) +
  geom_point(size=4)+geom_hline(yintercept = 0.5)+
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )

g_fdr <- df|> ggplot(aes(term,fdr,color=model)) + 
  geom_segment( aes(x=term, xend=term, y=0, yend=fdr)) +
  geom_point(size=4)+geom_hline(yintercept = 0.5)+
  theme_light() +
  coord_flip() + 
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
ggpubr::ggarrange(g_p.value,g_fdr,common.legend = TRUE)
```

