---
title: "EnWAS: Systolic-Blood Pressure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libs and Load data
The process of load libs and data is the same as [EnWAS sample](https://ccb-hms.github.io/Imputation/7_enwas/EnWAS_simple.html).

```{r data, warning=FALSE,message=FALSE,echo=FALSE}
# source("../6_nhanes_data/phesant.R")

library(DBI)
# library(broom)
library(splines)
# library(stringr)
library(dplyr)
library(ggplot2)
library(EnWAS)

exposure_vars <-
  read.delim("../../data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
  
  cols <-
    'SEQN,BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA,RIDRETH1, INDFMPIR, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)
  
  data
  
}

nhanes_data <- load_data(exposure_cols) 
data_phs <- phesant(nhanes_data)

data <- data_phs$data
phs_res <- data_phs$data_types

```

## Query Extra data 
This part loads the blood pressure data and merges it with the dietary and demographic data in the above section.

```{r query, echo=TRUE}
nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
# demo <- dbGetQuery(nhanes_db, "select * from demo")
# cholesterol <- dbGetQuery(nhanes_db, "select * from cholesterol")
# BPXDI2,BPXSY1
blood_pressure <- dbGetQuery(nhanes_db, "select SEQN,BPXSY1,years from blood_pressure where BPXSY1 IS NOT NULL")
dbDisconnect(nhanes_db)

```

## BPXSY1 - Systolic: Blood pres (1st rdg) mm Hg

The following plot shows that the 

```{r BPXSY1, echo=TRUE,warning=FALSE}

data <- merge(blood_pressure, data, by = c("SEQN",'years'))

ggplot(data,
         aes(
           x = RIDAGEYR,
           y = BPXSY1,
           colour = RIAGENDR
         )) +
  geom_point(alpha = 0.1) +
  geom_smooth(
    method = lm,
    formula = y ~ ns(x, knots = seq(20, 80, by = 5)),
    size = 1
  )+
  geom_smooth(method = lm, formula = y ~ x)


ggplot(data, aes(x=BMXBMI, y=BPXSY1) ) + 
  geom_point(aes(colour=RIAGENDR),alpha=0.1)+
  geom_density_2d()+geom_smooth(method = lm,formula = y ~ ns(x,df=7))

```


## Base Model

```{r func3, echo=TRUE,warning=F, out.width = '90%'}
linear_model <- 'BPXSY1 ~ RIDAGEYR*RIAGENDR + BMXBMI'

all_ns_model <-
  'BPXSY1 ~ ns(RIDAGEYR, knots = seq(20, 80, by = 10)) * RIAGENDR + ns(BMXBMI,knots = c(seq(15, 45, by = 5),seq(45,65,by=10)))'

```

## Plot residuals

```{r enthic, echo=TRUE,results = "asis"}
ethnicity <-
  c(
    'Mexican American',
    'Other Hispanic',
    'Non-Hispanic White',
    'Non-Hispanic Black',
    'Other Race'
  )
lm_base <- lm(as.formula(linear_model), data)
# summary(lm_base)
lm_df <-
  data.frame(
    residuals = lm_base$residual,
    ethnicity = data$RIDRETH1,
    gender = data$RIAGENDR,
    years = data$years,
    model = "lm"
  )
ns_base <- lm(as.formula(all_ns_model), data)
# summary(ns_base)
ns_df <-
  data.frame(
    residuals = scale(ns_base$residual),
    ethnicity = data$RIDRETH1,
    gender = data$RIAGENDR,
    years = data$years,
    model = "ns"
  )
levels(ns_df$ethnicity) <- ethnicity



```

```{r enthic2, echo=TRUE,results = "asis"}

ggplot(ns_df, aes(x = ethnicity, y = residuals, fill = gender)) + geom_boxplot() +
  scale_x_discrete(guide = guide_axis(angle = 45))

ggplot(ns_df, aes(x = years, y = residuals, fill = gender)) + geom_boxplot() +
  scale_x_discrete(guide = guide_axis(angle = 45))

res_df <- rbind(lm_df, ns_df)
ggplot(res_df, aes(x = model, y = residuals, fill = model)) + geom_boxplot() +
  scale_x_discrete(guide = guide_axis(angle = 45)) 

```






```{r residual1, echo=TRUE,warning=FALSE,message=FALSE,results = "asis"}
bin_mean <- function(bin){
  bin <- stringi::stri_replace_all_fixed(as.character(bin),'(','')
  bin <- stringi::stri_replace_all_fixed(as.character(bin),']','')
  bin <- as.numeric(unlist(stringi::stri_split_coll(bin,",")))
  mean(bin)
}

plot_residual <- function(model,ncalss=0){
  if (ncalss==0)
    ncalss <- floor(sqrt(length(model$fitted.values)))
  
  df <-
  data.frame(
    residuals = model$residuals,
    breaks = cut(model$fitted.values,breaks = ncalss)
  )
  df <- df %>% 
  group_by(breaks) %>% 
  summarize(mean = mean(residuals)
            )
  df$expected_value <- sapply(df$breaks, bin_mean)
  
ggplot(df,aes(expected_value,mean)) + geom_point() +
  geom_smooth(aes(expected_value,mean),method = "lm", formula = y ~  ns(x, df=7))+
  ylab("Average Risidual") + xlab("Expected Values")
}



plot_residual(lm_base)
plot_residual(ns_base)


```