---
title: "EnWAS: Diasatolic-Blood Pressure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libs and Load data
The process of load libs and data is the same as [EnWAS sample](https://ccb-hms.github.io/Imputation/7_enwas/EnWAS_simple.html).

```{r data, warning=FALSE,message=FALSE,echo=FALSE}
# source("../6_nhanes_data/phesant.R")

library(DBI)
# library(broom)
library(splines)
# library(stringr)
library(dplyr)
library(ggplot2)
library(EnWAS)

exposure_vars <-
  read.delim("../../data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
  
  cols <-
    'SEQN,BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA,RIDRETH1, INDFMPIR, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)
  
  data
  
}

nhanes_data <- load_data(exposure_cols) 
data_phs <- phesant(nhanes_data)

data <- data_phs$data
phs_res <- data_phs$data_types

```

## Query Extra data 

```{r query, echo=TRUE}
nhanes_db <- dbConnect(RSQLite::SQLite(), "../../nhanes.sqlite")
# demo <- dbGetQuery(nhanes_db, "select * from demo")
# cholesterol <- dbGetQuery(nhanes_db, "select * from cholesterol")
# BPXDI2,BPXSY1
blood_pressure <- dbGetQuery(nhanes_db, "select SEQN,BPXDI1,years from blood_pressure where BPXDI1 IS NOT NULL")
dbDisconnect(nhanes_db)
data <- merge(blood_pressure, data, by = c("SEQN",'years'))

```


## Run EnWAS ( BPXDI1 - Diastolic: Blood pres (1st rdg) mm Hg )

```{r func3, echo=TRUE,warning=F, out.width = '90%'}
linear_model <- 'BPXDI1 ~ RIDAGEYR*RIAGENDR + BMXBMI'
linear_res2 <- enwas(linear_model, exposure_vars, data)


all_ns_model <-
  'BPXDI1 ~ ns(RIDAGEYR, knots = seq(20, 80, by = 10)) * RIAGENDR + ns(BMXBMI,knots = c(seq(15, 45, by = 5),seq(45,65,by=10)))'
all_ns_res <- enwas(all_ns_model, exposure_vars, data)


lm_inverse_res <- enwas(linear_model, exposure_vars, data,inv = TRUE)
ns_inverse_res <- enwas(all_ns_model, exposure_vars, data,inv = TRUE)


```


## Compare linear regression with spline regression.



```{r res3, echo=TRUE,warning=F, out.width = '90%'}
# forest_plot(linear_res2$enwas_res)


forest_plot_mult(
  list(
    linear = linear_res2$enwas_res,
    ns = all_ns_res$enwas_res
  )
)
```


```{r res4, echo=TRUE,warning=F, out.width = '90%'}

forest_plot_mult(
  list(
    linear = linear_res2$enwas_res,
    lm_inv = lm_inverse_res$enwas_res
  )
)

  
```


## Residuals

```{r resid2, echo=TRUE,results = "asis"}
library(ggpubr)

lm_base <- lm(as.formula(linear_model), data)
lm_df <-
  data.frame(
    residuals = lm_base$residual,
    gender = data$RIAGENDR,
    DR1TMOIS = data$DR1TMOIS
  )
ns_base <- lm(as.formula(all_ns_model), data)
ns_df <-
  data.frame(
    residuals = ns_base$residual,
    DR1TMOIS = data$DR1TMOIS,
    gender = data$RIAGENDR
  )

g_lm <- ggplot(lm_df, aes(x=DR1TMOIS, y=residuals) ) + 
  geom_point(aes(colour=gender),alpha=0.1)+
  geom_smooth(method = lm,formula = y ~ ns(x,df=7)) + ggtitle("linear")

g_ns <- ggplot(lm_df, aes(x=DR1TMOIS, y=residuals) ) + 
  geom_point(aes(colour=gender),alpha=0.1)+
  geom_smooth(method = lm,formula = y ~ ns(x,df=7))+ggtitle("spline")

ggarrange(g_lm,g_ns,common.legend = TRUE)
```

