---
title: "Combine Data and Analysis"
author: "Laha Ale"
date: '2022-06-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libs

```{r libs,warning=FALSE,message=FALSE}
library(nhanesA)
library(knitr)
library(corrplot)
```

## Tables

```{r tables}
diet_tables <- c(
  "DR1TOT_C",
  "DR1TOT_D",
  "DR1TOT_E",
  "DR1TOT_F",
  "DR1TOT_G",
  "DR1TOT_H",
  "DR1TOT_I",
  "DR1TOT_J"
)

demo_tables <- c(
  "DEMO_C",
  "DEMO_D",
  "DEMO_E",
  "DEMO_F",
  "DEMO_G",
  "DEMO_H",
  "DEMO_I",
  "DEMO_J"
)

```

## Functions

```{r funcs}
load_nhanes_table <- function(t_name, data_path = "./data") {
  if (!dir.exists(data_path)) {
    dir.create(data_path)
  }
  
  file <- paste0(t_name, ".csv")
  dest_file <- file.path(data_path, file)
  tabl <- nhanes(t_name)
  if (!file.exists(dest_file)) {
    write.csv(tabl, dest_file, row.names = FALSE)
  } else{
    tabl <- read.csv(dest_file)
  }
  tabl
}


read_combine_data <- function(tabl_list) {
  com_cols <- c(colnames(load_nhanes_table(tabl_list[1])),"source")
  
  df_data <-
    data.frame(data.frame(matrix(
      ncol = length(com_cols), nrow = 0
    )))
  
  colnames(df_data) <- com_cols
  
  for (tb in tabl_list) {
    tmp_tb <-  load_nhanes_table(tb)
    tmp_tb$source <- rep(strsplit(tb,"_")[[1]][2],nrow(tmp_tb))
    com_cols <- intersect(com_cols, colnames(tmp_tb))
    df_data <- rbind(df_data[, com_cols], tmp_tb[, com_cols])
  }
  
  df_data
}


clip_data <- function(group, com_tb, table_list, miss_threshold=0.2){
  miss_rate <- sapply(com_tb, function(x) sum(is.na(x)))/nrow(com_tb)
  var_descr <-  nhanesTableVars(group,table_list[1])
  var_descr[nrow(var_descr) + 1,] <- c("source", "data source")

  var_descr <- var_descr[var_descr$Variable.Name %in% colnames(com_tb),] 
  miss_rate['source'] <- 0
  var_descr$miss_rate = miss_rate[var_descr$Variable.Name]
  var_descr$miss_rate_pct = paste(round(100*var_descr$miss_rate, 2), "%", sep="")
  
  
  var_descr <- var_descr[,c('Variable.Name','miss_rate_pct','Variable.Description','miss_rate')]
  clipped_var <- var_descr[var_descr$miss_rate < miss_threshold,]
  
  clipped_data <- com_tb[,c("SEQN",clipped_var$Variable.Name)]
  
  return(list(clipped_data,clipped_var))
}

```

## Combine data sets

```{r comb}
demo_data <- read_combine_data(demo_tables)
diet_data <- read_combine_data(diet_tables)
```

## Clip data sets

```{r miss_clipp,warning=FALSE}
library(dplyr)
library(ggplot2)
library(naniar)
library(visdat)
r_demo <- clip_data("DEMO", demo_data, demo_tables)

clipped_demo <- r_demo[[1]]
clipped_var_demo <- r_demo[[2]]

kable(clipped_var_demo[,c("Variable.Name", 'miss_rate_pct', 'Variable.Description')])

r_diet <- clip_data("DIET", diet_data, diet_tables)

clipped_diet <- r_diet[[1]]
clipped_var_diet <- r_diet[[2]]

kable(clipped_var_diet[,c("Variable.Name", 'miss_rate_pct', 'Variable.Description')])

```

## Missing correlation for DEMO

```{r missing}
gg_miss_var(clipped_demo,show_pct = TRUE)+theme(axis.text.y = element_text(angle = 45))

correlation <- cor(is.na(clipped_demo[,clipped_var_demo[clipped_var_demo$miss_rate>0,]$Variable.Name]))
# correlation[is.na(correlation)] <- 0
heatmap(correlation)

corrplot(correlation, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```

## Missing correlation for DIET

```{r missing2,fig.asp = 0.8, fig.width = 7, out.width = "100%"}
gg_miss_var(clipped_diet,show_pct = TRUE)+theme(axis.text.y = element_text(angle = 45))
correlation <- cor(is.na(clipped_diet[,clipped_var_diet[clipped_var_diet$miss_rate>0,]$Variable.Name]))
# correlation[is.na(correlation)] <- 0
heatmap(correlation)

corrplot(correlation, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```

## Missing 9.7% variables

Many of those variables are not very interesting

```{r missing3,fig.asp = 0.8, fig.width = 7, out.width = "100%"}
die_miss_str <- cor(is.na(clipped_diet[, clipped_var_diet[round(clipped_var_diet$miss_rate,3)==0.097,]$Variable.Name]))
heatmap(die_miss_str)
corrplot(die_miss_str, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)
```


## Merge the data by SEQN

```{r merge}
# NOTE: SEQN may not unique it is only unique in the same consequcit year
merged_df <- merge(clipped_demo, clipped_diet, by = c("SEQN","source"))
merged_df <- merged_df[merged_df$RIDAGEYR>21,]
dim(merged_df)
write.csv(merged_df,"./data/merged_data.csv",row.names=FALSE)
```



