---
title: "Data Summary"
date: "Updated on : `r date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libs and Load data
The process of load libs and data is the same as [EnWAS sample](https://ccb-hms.github.io/Imputation/7_enwas/EnWAS_simple.html).

```{r data, warning=FALSE,message=FALSE,echo=FALSE}
# source("../6_nhanes_data/phesant.R")

library(DBI)
# library(broom)
library(splines)
# library(stringr)
library(dplyr)
library(ggplot2)
library(EnWAS)
library(Hmisc)

exposure_vars <-
  read.delim("./data/select_vars.txt", header = FALSE)$V1
exposure_cols <- paste(exposure_vars, collapse = ", ")


# Load data and convert data types according to PHESEANT.
# Return data set and PHESEANT results.
load_data <- function(exposure_cols) {
  nhanes_db <- dbConnect(RSQLite::SQLite(), "./nhanes.sqlite")

  
  cols <-
    'SEQN,BMXWAIST, RIDAGEYR, BMXHT, BMXBMI, BMXWT, RIAGENDR,SDMVPSU,SDMVSTRA,RIDRETH1, INDFMPIR, years,'
  data_sql <-
    paste('SELECT', cols, exposure_cols, 'FROM merged_table')
  
  data <- dbGetQuery(nhanes_db, data_sql)
  data <- na.omit(data)
  dbDisconnect(nhanes_db)

  data
  
}

nhanes_data <- load_data(exposure_cols) 
data_phs <- phesant(nhanes_data)

data <- data_phs$data
phs_res <- data_phs$data_types


nhanes_db <- dbConnect(RSQLite::SQLite(), "./nhanes.sqlite")

# BPXDI1,BPXSY1
blood_BPXSY1 <- dbGetQuery(nhanes_db, "select SEQN,BPXSY1,years from blood_pressure where BPXSY1 IS NOT NULL and BPXSY1 <> 0")

data1 <- merge(blood_BPXSY1, data, by = c("SEQN",'years'))



blood_BPXDI1 <- dbGetQuery(nhanes_db, "select SEQN,BPXDI1,years from blood_pressure where BPXDI1 IS NOT NULL and BPXDI1 <> 0")

data <- merge(blood_BPXDI1, data, by = c("SEQN",'years'))

dbDisconnect(nhanes_db)
```

## Summary

```{r query, echo=TRUE}
CI <- function(data)
{
  upper <- round(quantile(data,0.975),2)
  lower <- round(quantile(data,0.025),2)
  paste0("(",lower,"-", upper,")")
}
mean1 <- function(data){
  round(mean(data),2)
}
sum_data <- function(data,data1,condition){
  print("------------mean--------------------------------")
  print(sapply(c(data[c('BMXBMI','BPXDI1','BMXWAIST')],data1['BPXSY1']),mean1))
  print("------------CI------------------------------------")
  print(sapply(c(data[c('BMXBMI','BPXDI1','BMXWAIST')],data1['BPXSY1']),CI))
}

sum_data(data[data$RIDAGEYR<59,],data1[data1$RIDAGEYR<59,])

sum_data(data[data$RIDAGEYR>=59,],data1[data1$RIDAGEYR>=59,])

sum_data(data[data$RIAGENDR=="Male",],data1[data1$RIAGENDR=="Male",])
sum_data(data[data$RIAGENDR=="Female",],data1[data1$RIAGENDR=="Female",])

ethnicity <-
  c(
    'Mexican American',
    'Other Hispanic',
    'Non-Hispanic White',
    'Non-Hispanic Black',
    'Other Race'
  )


sum_data(data[data$RIDRETH1==1,],data1[data1$RIDRETH1==1,])
sum_data(data[data$RIDRETH1==2,],data1[data1$RIDRETH1==2,])
sum_data(data[data$RIDRETH1==3,],data1[data1$RIDRETH1==3,])
sum_data(data[data$RIDRETH1==4,],data1[data1$RIDRETH1==4,])
sum_data(data[data$RIDRETH1==5,],data1[data1$RIDRETH1==5,])


# education
nhanes_db <- dbConnect(RSQLite::SQLite(), "./nhanes.sqlite")
demo <- dbGetQuery(nhanes_db, "select SEQN, DMDEDUC2 from demo where DMDEDUC2 IS NOT NULL")


data <- merge(demo, data, by = "SEQN")
data1 <- merge(demo, data1, by = "SEQN")
dbDisconnect(nhanes_db)

sum_data(data[data$DMDEDUC2==1,],data1[data1$DMDEDUC2==1,])
sum_data(data[data$DMDEDUC2==2,],da?ta1[data1$DMDEDUC2==2,])
sum_data(data[data$DMDEDUC2==3,],data1[data1$DMDEDUC2==3,])
sum_data(data[data$DMDEDUC2==4,],data1[data1$DMDEDUC2==4,])
sum_data(data[data$DMDEDUC2==5,],data1[data1$DMDEDUC2==5,])



blood_pres <- dbGetQuery(nhanes_db,"select * from blood_pressure inner join demo on blood_pressure.SEQN=demo.SEQN")
blood_pres <- blood_pres[blood_pres$RIDAGEYR>20,]
knitr::kable(cor(na.omit(blood_pres[c("BPXDI1","BPXDI2","BPXDI3")])))
knitr::kable(cor(na.omit(blood_pres[c("BPXSY1","BPXSY2","BPXSY3")])))
```




