---
title: "PHSEANT express"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libs

```{r libs}
library(nhanesA)
library(dplyr)
library(ggplot2)
```

## Plots same value ratio

```{r pressure, fig.asp = 0.8, fig.width = 7, out.width = "100%"}
df <- read.csv("./data/merged_data.csv")
cnt_data <- nrow(df)


num_data <- df |> select_if(is.numeric) |> select_if(~!is.integer(.x))   

same_ratio <- round(1-sapply(num_data, function(x) n_distinct(x))/cnt_data,4)

data <- data.frame(
  x=names(same_ratio),
  y=same_ratio
)
same_ratio

ggplot(data, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )+theme(axis.text.y = element_text(angle = 45))

```



## plot distribution of continuous

```{r plot2,results='asis',warning=FALSE,message=FALSE}
library(ggplot2)
library(hrbrthemes)
library(GGally)
  
phesant <- function(df){
  
  cnt_data <- nrow(df)
  
  # set default data type as unknown
  data_types <- rep('unknown',ncol(df))
  names(data_types) <- colnames(df)
  
  # **********************continuous started*******************************
  num_data <- df |> select_if(is.numeric) |> select_if(~!is.integer(.x))   
  same_ratio <- round(1-sapply(num_data, function(x) n_distinct(x))/cnt_data,4)
  
  continous_cols <- names(same_ratio[same_ratio < 0.35])
  
  
  # remove less than 10 participants
  num_data <- num_data |> select(-continous_cols)
  distinct_cnt <- sapply(num_data, function(x) n_distinct(x))
  continous_cols <- c(continous_cols,names(distinct_cnt[distinct_cnt>20]))
  
  data_types[continous_cols] <- 'continuous'
  paticipants_cnt <- sapply(df, function(x) sum(!is.na(x)))
  data_types[names(paticipants_cnt[paticipants_cnt<10])]="remove"
  
  # **********************continuous end***********************************
  
  
  data_types
  
  
}


retrive_var_infor <- function(var){
  bmx_cols <- read.delim("data/bmx_cols.txt",header = FALSE)$V1
  diet_cols <- read.delim("data/diet_cols.txt",header = FALSE)$V1
  group <- 'DEMO'
  table <-  'DEMO_D'
  if(var %in% bmx_cols){
    group <- 'EXAM'
    table <-  'BMX_D'
  }else if(var %in% diet_cols){
    group <- 'DIET'
    table <-  'DR1TOT_D'
  }
  vars<- nhanesTableVars(group,table)
  var_dsc <- vars[vars$Variable.Name==var,]$Variable.Description
  var_inf <- nhanesTranslate(table,var)
  
  c(var_dsc,var_inf)
}

plot_continous <- function(continous_cols,df){
  for (con in continous_cols){
    vars <- retrive_var_infor(con)
    p <- ggplot(data=df, aes_string(x=con, group='years', fill='years')) +
      geom_density(adjust=1.5, alpha=.25) + labs(caption = as.character(vars[[2]][1,]))+
      xlab(vars[[1]])
      print(p)
    
  } 
}


data_types <- phesant(df)

continuous_cols <- names(data_types[data_types=='continuous'])
plot_continous(continuous_cols,df)

```

## plot order

```{r plot3,results='asis',message=FALSE,warning=FALSE}
# library(knitr)
# num_data <- num_data |> dplyr::select(-continous_cols)
# # remove less than 10 participants, otherwise assign to order
# paticipants_cnt <- sapply(num_data, function(x) sum(!is.na(x)))
# 
# 
# data <- data.frame(
#   'distinct_cnt'= distinct_cnt
# )
# kable(data)
# order_cols <- names(paticipants_cnt[paticipants_cnt>10])
# data_types[names(paticipants_cnt[paticipants_cnt<10])]="remove"
# data_types[order_cols] <- 'order' 
# for (od in order_cols) {
#     p <- ggplot(data=df, aes_string(x=od, group='years', fill='years')) +
#     geom_histogram(adjust=1.5, alpha=.35) +
#     theme_ipsum()
#   print(p)
# }
```